---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.ci/ for running pre-commit in the cloud

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.3.1
    hooks:
      - id: yamlfix

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        language: docker_image
        types: [dockerfile]
        entry: ghcr.io/hadolint/hadolint hadolint

  - repo: https://github.com/snakemake/snakefmt
    rev: v0.8.0
    hooks:
      - id: snakefmt
        name: snakefmt
        description: 'Snakefmt: The uncompromising Snakemake formatter'
        entry: snakefmt
        language: python
        language_version: python3
        require_serial: true
        files: \.smk$|Snakefile
